title: Ryan Condron
tagline: Ruby on Rails Developer
email: rebelwebdevelopment@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an experienced web developer with a focus on Ruby on Rails and Linux.
twitter_username: rebelwebdev
github_username:  rebelweb

development:
    url: "https://rebelweb.github.io" # the base hostname & protocol for your site
    baseurl: "" # the subpath of your site, e.g. /blog

production:
  url: "https://rebelweb.github.io" # the base hostname & protocol for your site
  baseurl: "" # the subpath of your site, e.g. /blog


# Build settings
markdown: kramdown

collections:
  projects:
    output: true
